#reference website to learn more https://editor.swagger.io/
openapi: 3.0.3
info:
  title: LocaLoyalty API
  description: API routes for LocaLoyalty business website and customer mobile app ***You must be logged into clerk from the front-end to test API because it is protected by the clerk middleware***
  version: "1.0.0"
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url:
    description:

tags:
  - name: business
    description: APIs for the website that small business owners will access
  - name: customer
    description: APIs for the mobile app that end-users will access

paths:
  /business/sample:
    get:
      tags:
        - business
      summary: Sample endpoint
      description: Returns a sample data
      operationId: getBusinessSampleAPI
      responses:
        200:
          description: Successful response
  /business/profile:
    get:
      tags:
        - business
      summary: Get the current profile data of the user
      description: Queries user profile table in DB for data and sends it back to the front-end. No params required because the header includes the clerk ID already
      operationId: getBusinessProfile
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusinessProfile"
        500:
          description: User Does not exist in DB
    post:
      tags:
        - business
      summary: Update user profile info
      description: Updates the user profile information if valid. UserID is taken from header
      operationId: updateBusinessProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BusinessProfile"
      responses:
        200:
          description: Successful response
        500:
          description: Failure
  /customer/vendors:
    get:
      tags:
        - customer
      summary: Get the list of all vendors
      description: Display all of the registered vendors whether or not they are associated with this particular user
      operationId: getAllVendors
      responses:
        200: 
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VendorList"
        500:
          description: Error fetching vendors
  /customer/{userId}/loyalty-cards:
    get:
      tags: 
        - customer
      summary: Get the list of vendors associated with a particular user
      description: Display all of the vendors associated with a particular user. UserID is taken from the auth field of header
      operationId: getAllLoyaltyCards
      parameters:
        - name: userId
          in: path
          description: ID of the current user
          required: true
          schema:
            type: integer
            format: int64
  /business/loyalty-program:
    get:
      tags:
        - business
      summary: Get the current loyalty program data of the user
      description: Queries user profile and loyalty program table in DB for data and sends it back to the front-end. No params required because the header includes the clerk ID already
      operationId: getBusinessLoyaltyProgram
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusinessLoyaltyProgram"
        500:
          description: User Does not exist in DB
    post:
      tags:
        - business
      summary: Update business owner's loyalty program and rewards info
      description: Updates the user loyalty program and rewards if valid. UserID is taken from header. A reward_id of null indicates that the reward is a new one and requires a DB insertion
      operationId: updateBusinessLoyaltyProgram
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BusinessLoyaltyProgram"
      responses:
        200:
          description: Successful response
        500:
          description: Failure
components:
  schemas:
    BusinessProfile:
      type: object
      properties:
        businessName:
          type: string
          example: "Zhang's Bakery"
        address:
          type: string
          example: "123 real address NE"
        city:
          type: string
          example: "Calgary"
        province:
          type: string
          example: "Alberta"
        postalCode:
          type: string
          example: "A1B2C3"
        merchantID:
          type: string
          example: "123456789"
        apiKey:
          type: string
          example: "oqpweiopqwepioqiweop"
        businessImage:
          type: string
          description: "Either a file or a url that will be used to render the image"
        businessLogo:
          type: string
          description: "Either a file or a url that will be used to render the image"
        description:
          type: string
          example: "this is a really cool store"
    VendorList:
      type: array
      items: 
        $ref: '#/components/schemas/Vendor'
    Vendor:
      type: object
      required:
        - vendor_id
        - name
        - email
        - spending_per_point
        - max_points
      properties:
        vendor_id:
          type: integer
          format: int32
          description: The unique identifier for the vendor
        name:
          type: string
          maxLength: 256
          description: The name of the vendor
        email:
          type: string
          maxLength: 256
          description: The email address of the vendor
        address:
          type: string
          maxLength: 256
          description: The physical address of the vendor
        phone:
          type: string
          maxLength: 16
          description: The contact phone number for the vendor
        description:
          type: string
          description: A description of the vendor
        color:
          type: string
          maxLength: 16
          description: A color theme associated with the vendor
        reward_program_details:
          type: string
          description: Details about the vendor's reward program
        spending_per_point:
          type: number
          format: double
          description: The amount of spending required to earn a point
        max_points:
          type: integer
          format: int32
          description: The maximum number of points a customer can earn
    BusinessLoyaltyProgram:
      type: object
      properties:
        stampLife:
          type: number
          example: null
        stampCount:
          type: number
          example: 6
        scaleAmount:
          type: string
          example: "5"
        definedRewards:
          type: array
          items:
            $ref: "#/components/schemas/Reward"
    Reward:
      type: object
      properties:
        reward_id:
          type: number
          example: 8
        title:
          type: string
          example: "Free Pineapple Bun"
        requiredStamps:
          type: number
          example: 3
